[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "2yQwG6tLmpoiuoHsJypPQ5eKHnHy8gwRkNiCWAohg6cS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "yarn run jest --preset ts-jest"
